/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.psc.sgo.apresentacao;

import br.edu.ifnmg.psc.sgo.aplicacao.Aplicacao;
import br.edu.ifnmg.psc.sgo.aplicacao.Usuario;

import java.util.List;
import javax.swing.JOptionPane;
import br.edu.ifnmg.psc.sgo.aplicacao.UsuarioRepositorio;

/**
 *
 * @author Douglas_Castro
 */
public class TelaLogin extends javax.swing.JFrame {

    UsuarioRepositorio dao = Repositorios.getUsuarioRepositorio();

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLogin = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        textUsuario = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autenticação");
        getContentPane().setLayout(null);

        btLogin.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btLogin.setText("Acessar");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btLogin);
        btLogin.setBounds(640, 380, 100, 30);

        btSair.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair);
        btSair.setBounds(520, 380, 110, 30);

        textUsuario.setBackground(new java.awt.Color(254, 254, 254));
        textUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textUsuario.setForeground(new java.awt.Color(132, 132, 132));
        textUsuario.setText("Usuário");
        textUsuario.setSelectionStart(-1);
        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(textUsuario);
        textUsuario.setBounds(410, 230, 450, 40);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 56)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><center>SGO</center>Login</html>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 70, 430, 140);

        txtSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtSenha);
        txtSenha.setBounds(410, 300, 450, 40);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iStock_000031663298_Large_1.jpg"))); // NOI18N
        jLabel1.setText("Tela Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -60, 1450, 870);
        jLabel1.getAccessibleContext().setAccessibleName("Tela login");

        setSize(new java.awt.Dimension(1406, 837));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed


    }//GEN-LAST:event_textUsuarioActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // botao tela login sair
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        //botao acessar:
        Usuario p = new Usuario(0, null, textUsuario.getText(), String.valueOf(txtSenha.getPassword()));

        List<Usuario> lista = dao.Buscar(p);

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Usuario ou senha invalido!");

        } else {

            Aplicacao.setUsuario(lista.get(0));

            TelaPrincipal principal = new TelaPrincipal();

            principal.setTelalogin(this);

            principal.setVisible(true);
            this.setVisible(false);

        }


    }//GEN-LAST:event_btLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.TextField textUsuario;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
