/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.psc.sgo.apresentacao;

import br.edu.ifnmg.psc.sgo.aplicacao.Funcionario;
import br.edu.ifnmg.psc.sgo.aplicacao.FuncionarioRepositorio;
import br.edu.ifnmg.psc.sgo.aplicacao.ItemPedido;
import br.edu.ifnmg.psc.sgo.aplicacao.ObrasEServicos;
import br.edu.ifnmg.psc.sgo.aplicacao.ObrasEServicosRepositorio;
import br.edu.ifnmg.psc.sgo.aplicacao.StatusAndamento;
import br.edu.ifnmg.psc.sgo.aplicacao.Trabalho;
import br.edu.ifnmg.psc.sgo.aplicacao.TrabalhoFuncionario;
import br.edu.ifnmg.psc.sgo.aplicacao.TrabalhoFuncionarioRepositorio;
import br.edu.ifnmg.psc.sgo.aplicacao.ViolacaoRegraNegocioException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author mauricio
 */
public class TrabalhoEditar extends TelaEdicao<Trabalho> {
    
    FuncionarioRepositorio funcionarios = Repositorios.getFuncionarioRepositorio();
    ObrasEServicosRepositorio obrasEServicos = Repositorios.getObrasEServicosRepositorio();
    TrabalhoFuncionarioRepositorio trabalhos = Repositorios.getTrabalhoFuncionarioRepositorio();
    List<Funcionario> listagem = null;
    DefaultListModel model = new DefaultListModel();
    
    DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm");
    
    /**
     * Creates new form TrabalhoEditar
     */
    public TrabalhoEditar() {
        super();
        initComponents();
                
        entidade = new Trabalho();
        
        preencheCbx(obrasEServicos, cbxObras);
                
        ComboBoxModel model = new DefaultComboBoxModel(StatusAndamento.values());               
        cbxAndamento.setModel(model);
        
        txtDataAtual.setText(df.format(new Date()));
        
        listagem = funcionarios.Buscar(null);
        
        preencheLista(listagem);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblObra = new javax.swing.JLabel();
        cbxObras = new javax.swing.JComboBox<>();
        lblNome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFuncionarios = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        lblDataInicio = new javax.swing.JLabel();
        lblDataTermino = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbxAndamento = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtDataAtual = new javax.swing.JTextField();
        txtDataTermino = new com.toedter.calendar.JDateChooser();
        txtDataInicio = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Gerenciar Trabalho");

        lblObra.setText("Obra e/ou Serviço: *");

        cbxObras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNome.setText("Funcionário: *");

        jScrollPane1.setViewportView(lstFuncionarios);

        lblDataInicio.setText("Data Inicio: *");

        lblDataTermino.setText("Data Término: *");

        jLabel1.setText("Andamento: *");

        cbxAndamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save_37110.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancel_icon-icons.com_73703.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtDataAtual.setEditable(false);

        jLabel2.setText("Última modificação:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObra)
                            .addComponent(lblNome)
                            .addComponent(jLabel1)
                            .addComponent(lblDataTermino)
                            .addComponent(lblDataInicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxObras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbxAndamento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDataTermino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                                        .addGap(153, 153, 153)
                                        .addComponent(btnCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObra)
                    .addComponent(cbxObras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(153, 153, 153))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(btnCancelar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDataInicio)
                                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDataTermino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxAndamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setBounds(260, 55, 826, 443);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        int[] indexes = lstFuncionarios.getSelectedIndices();
        TrabalhoFuncionario selecionado = new TrabalhoFuncionario();

        for (int i : indexes)
            try {                
                selecionado.setFuncionario( listagem.get(i) );
                entidade.addFuncionario(selecionado);                                
            } catch (ViolacaoRegraNegocioException ex) {
                Logger.getLogger(TrabalhoEditar.class.getName()).log(Level.SEVERE, null, ex);
            }       
        salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxAndamento;
    private javax.swing.JComboBox<String> cbxObras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JLabel lblDataTermino;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObra;
    private javax.swing.JList<String> lstFuncionarios;
    private javax.swing.JTextField txtDataAtual;
    private com.toedter.calendar.JDateChooser txtDataInicio;
    private com.toedter.calendar.JDateChooser txtDataTermino;
    // End of variables declaration//GEN-END:variables

    @Override
    public void carregaCampos() {
        cbxObras.setSelectedItem( entidade.getObraEServico() );
        List<TrabalhoFuncionario> lista = null;   
        lista = entidade.getFuncionarios();             

        if (lista != null)
            preencheTabela(lista);
        txtDataInicio.setDateFormatString(entidade.getDataInicio());
        txtDataTermino.setDateFormatString( entidade.getDataTermino());
        cbxAndamento.setSelectedItem( entidade.getAndamento() );
        txtDataAtual.setText( entidade.getUltimaModificacao() );   
    }

    @Override
    public void carregaObjeto() throws ViolacaoRegraNegocioException {
        entidade.setDataInicio((String) df.format(txtDataInicio.getDate()) );
        entidade.setDataTermino((String) df.format(txtDataTermino.getDate()) );
        entidade.setUltimaModificacao((String) df.format(new Date()));
        entidade.setAndamento( (StatusAndamento) cbxAndamento.getSelectedItem());
        entidade.setObraEServico((ObrasEServicos) cbxObras.getSelectedItem());
        entidade.setFuncionarios( entidade.getFuncionarios());
    }

    @Override
    public boolean verificarCamposObrigatorios() {
        return  txtDataInicio.getDate() != null || 
                txtDataTermino.getDate() != null ||
                cbxAndamento.getSelectedItem() != null ||
                lstFuncionarios.getSelectedIndices() != null ||
                cbxObras.getSelectedItem() != null;
    }
    
    private void preencheLista(List<Funcionario> listagem){                        
        int i = 0;                
        for (Funcionario f : listagem) {            
            model.add(i,f.getId()+" - "+f.getCpf()+" "+f.getNome()+"    "+f.getCargo());
            i++;                
        }
        lstFuncionarios.setModel(model);
    }
    
    public void preencheTabela(List<TrabalhoFuncionario> listagem) {
        int i = 0;  
        for(TrabalhoFuncionario f : listagem) {            
            model.add(i,f.getId()+" - "+f.getFuncionario().getCpf()+" "+f.getFuncionario().getNome()+"    "+f.getFuncionario().getCargo());
            i++;                
        }
        lstFuncionarios.setModel(model);
    }
}
