/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teste;

import br.edu.ifnmg.psc.sgo.aplicacao.Empresa;
import br.edu.ifnmg.psc.sgo.aplicacao.EmpresaRepositorio;
import br.edu.ifnmg.psc.sgo.aplicacao.FornecedorRepositorio;
import br.edu.ifnmg.psc.sgo.aplicacao.ViolacaoRegraNegocioException;
import br.edu.ifnmg.psc.sgo.apresentacao.Cliente;
import br.edu.ifnmg.psc.sgo.apresentacao.FuncionarioEditar;
import br.edu.ifnmg.psc.sgo.persistencia.EmpresaDAO;
import br.edu.ifnmg.psc.sgo.persistencia.FornecedorDAO;
import java.awt.Font;
import java.sql.SQLException;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author mauricio
 */
public class Principal {
    public static void main (String[] args) throws ViolacaoRegraNegocioException, ClassNotFoundException, SQLException{
        /*Empresa e = new Empresa();
        
        e.setNome("jhghfdsf");
        e.setCnpj("4556");
        e.setRua("4");
        e.setBairro("4");
        e.setNumero("4");
        e.setFone("44444444444");
        e.setEmail("4");
        
        EmpresaRepositorio repositorio = new EmpresaDAO();
                    
        repositorio.Salvar(e);*/
        
        Cliente c = new Cliente();
        
        c.setCpf("11111111111");
        
        System.out.printf("%s \n\n",c.getCpf());
    }
    // Variables declaration - do not modify
    private JLabel lblEndereco;
    private JTextField txtNumero;
    // End of variables declaration

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")
    public void initComponents(FuncionarioEditar funcionarioEditar) {
        lblEndereco = new JLabel();
        txtNumero = new JTextField();
        lblEndereco.setFont(new Font("Ubuntu", 1, 13)); // NOI18N
        lblEndereco.setText("Endere\u00e7o:");
        txtNumero.setToolTipText("N\u00famero");
        funcionarioEditar.setClosable(true);
        funcionarioEditar.setTitle("Editar Funcion\u00e1rio");
        funcionarioEditar.setToolTipText("");
        GroupLayout layout = new GroupLayout(funcionarioEditar.getContentPane());
        funcionarioEditar.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 621, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 463, Short.MAX_VALUE));
        funcionarioEditar.setBounds(390, 130, 632, 491);
    } // </editor-fold>
}
